name: Call Main
on: 
  workflow_dispatch:
    inputs:
      env:
        description: 'Branch name to check (default: develop)'
        required: false
        type: string
        default: 'dev'
        options:
          - dev
          - qa
          - stage
          - prod
jobs:
  call:
    uses: Muzzler/muzzle/.github/workflows/testpipeline.yml@main
    with:
      ref: ${{ github.ref_name }}
      env: ${{ github.event.inputs.env }}
      
